name: Release Nightly

on:
  schedule:
    # Fire every day at 7:00am UTC (Roughly before EU workday and after US workday)
    - cron: "0 7 * * *"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  RUST_BACKTRACE: 1

jobs:
  bundle-deb:
    name: Create a Linux Executable
    runs-on: ubuntu-22.04 # keep the version fixed to avoid libc and dynamic linked library issues
    steps:
      - name: Build
        run: cargo build --release --keep-going --verbose
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: zed-linux
          path: /
